# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ionplus_toolbox',
                'doc_host': 'https://dmitryhits.github.io',
                'git_url': 'https://github.com/dmitryhits/ionplus_toolbox',
                'lib_path': 'ionplus_toolbox'},
  'syms': {'ionplus_toolbox.core': {'ionplus_toolbox.core.foo': ('core.html#foo', 'ionplus_toolbox/core.py')}}}
